repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ./.venv/bin/ruff
        args:
          - check
          - --exit-non-zero-on-fix
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: ruff-format
        name: ruff-format
        entry: ./.venv/bin/ruff
        args: [ format ]
        language: system
        types: [ python ]
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: ./.venv/bin/mypy
        args:
          - ua_datasets
        language: system
        types: [ python ]
        pass_filenames: false
        always_run: true
      - id: uv-sort
        name: uv-sort
        entry: ./.venv/bin/uv-sort
        language: system
        pass_filenames: false
      - id: uv-lock
        name: uv-lock
        entry: uv
        args:
          - lock
          - --dry-run
        language: system
        pass_filenames: false
