default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pytest
        args: ["--config-file", "pyproject.toml"]
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check (uv)
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        stages: [pre-commit]
      # Additional push-stage checks mirroring CI (non auto-fixing, format check only)
      - id: ruff-format-check
        name: ruff format (check)
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: ruff-lint-check
        name: ruff check (no fix)
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: mypy-push
        name: mypy (push / non-blocking parity with CI)
        entry: uv run mypy || true
        language: system
        pass_filenames: false
        stages: [pre-push]
