name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install --upgrade uv

      - name: Sync dependencies
        run: uv sync --dev

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Lint (ruff format check)
        run: uv run ruff format --check .

      - name: Type check (mypy)
        run: uv run mypy || true  # remove '|| true' later to enforce strict

      - name: Test (pytest)
        run: uv run pytest -q --maxfail=1 --disable-warnings
