name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: patrick-kidger/action_update_python_project@v3
        with:
            python-version: "3.11"
            test-script: |
                python -m pip install pytest
                cp -r ${{ github.workspace }}/test ./test
                pytest  --disable-warnings
            pypi-token: ${{ secrets.pypi_token }}
            github-user: KyloRen1
            github-token: ${{ github.token }}
            email-user: ${{ secrets.email_user }}
            email-token: ${{ secrets.email_token }}
            email-server: ${{ secrets.email_server }}
            email-target: ${{ secrets.email_target }}
            email-starttls: 'true'